### ISSUE TITLE
Ntuples are not merged in MT mode.

### ISSUE THREAD

**Issue by ggalgoczi** [BNLNPPS/esi-g4-optical#3] opened 2024-08-02 16:46 UTC
AnalysisManager supports merging of Ntuples in MT mode. Expected behaviour is that once SetNtupleMerging(true) function is called, a single ROOT file is created. It is not an urgent problem for now but needs to be fixed later.

In RunAction.cc:
auto analysisManager = G4AnalysisManager::Instance(); //get the manager
analysisManager->SetNtupleMerging(true);

However one ROOT file is created for each thread. The following exception is written out:

-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : Analysis_W001
      issued by : G4RootNtupleFileManager::SetNtupleMergingMode
Merging ntuples requires G4AnalysisManager instance on master.
Setting was ignored.
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------

**Comment by buddhasystem** [comment] 2024-08-02 17:23
Ah! I think I know just the person to ask (i.e. who coded this feature). Stay tuned.

MT is a must, we've arrived to that conclusion a while ago.
Maybe there is an option we need to use.

**Comment by buddhasystem** [comment] 2024-09-17 19:45
Still on my to-do list...

**Comment by buddhasystem** [comment] 2024-09-19 22:31
Sent a request to the expert, they'll look at the code.

**Comment by ggalgoczi** [comment] 2024-09-21 15:42
Added as suggested by Makoto in 027ba5c
```
  RunAction* fRunAct = new RunAction(nullptr, _OutputFormat);
  SetUserAction(fRunAct);
```
in
`void ActionInitialization::BuildForMaster() `

Still getting segfault. Tried gdb debugger, got 

```
Downloading source file /build/gcc-14-OQFzmN/gcc-14-14-20240412/build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_string.h
std::operator<< <char, std::char_traits<char>, std::allocator<char> > (         
    __os=..., 
    __str=<error reading variable: Cannot access memory at address 0x58>)
    at /build/gcc-14-OQFzmN/gcc-14-14-20240412/build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_string.h:227
warning: 227	/build/gcc-14-OQFzmN/gcc-14-14-20240412/build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_string.h: No such file or directory
```

Not sure if this has something to do with Geant4.

**Comment by buddhasystem** [comment] 2024-10-11 21:53
OK, so it all has to do with properly doing "ActionInitialization" for master and other threads. I'm in the process of implementing this in the "optical2" folder, so this can be closed in this instance. Closing.

**Closed as completed by buddhasystem** 2024-10-11 21:53 UTC

**Comment by ggalgoczi** [comment] 2024-10-11 23:28
Thank you, I am really curious what is the solution with the newest G4 codebase. Could you drop it here once it is implemented?

**Comment by buddhasystem** [comment] 2024-10-12 00:54
> Thank you, I am really curious what is the solution with the newest G4 codebase. Could you drop it here once it is implemented?

Sure -- I'll finish the "optical2" -- hopefully soon -- and that would establish the pattern that works. I've been in contact with Makoto and Maurizio (who is the main Analysis Module guy) and they mentioned that the actions need to be initialized correctly for the master thread, and then separately for the other threads. This is not really intuitive, so having a recipe helps. I'm following the recipe now and will let you know when I'm done. As it is, it's not a bug in G4 proper.
